sprint-1
ClevertecFrontendLab/sprint1-TatianaRusak pull request #1
Opened 2023-01-30 18:51 UTC by TatianaRusak

2023-01-30 18:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675104866/content-window.png)

2023-01-30 19:01 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215569922-eee5623c-3ae0-42fe-ba29-a1ecb03a3841.png)
активный раздел должен быть выделен, проверти цвет заголовка и линии на соответствие макету

2023-01-30 19:02 UTC, SergeyGlazun commented
если сайт на русском то и список лучше на русском делать, если сайт на другом языке то у него будет предусмотрена кнопка для языка

2023-01-30 19:17 UTC, klichkovskiy requested changes

2023-01-30 19:17 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +                <span className='additional__prop-value'>
![image](https://user-images.githubusercontent.com/62481116/215572621-5e7209f0-85b9-4935-a562-76cf995c7e88.png)
Сделай п один столбец у тебя так на 320 и 768

2023-01-30 19:17 UTC, klichkovskiy commented on src/index.tsx
> +          {/* <Route path='profile' element={<Profile />} /> */}
Удали закомментированный код

2023-01-30 19:17 UTC, klichkovskiy commented on src/pages/offerta/offerta-page.tsx
> +export const OffertaPage = () => {
Это две одинаковые страницы с разным заголовком. Его можно передать пропсом

2023-01-30 19:17 UTC, klichkovskiy commented on src/components/navigation/navigation.tsx
> +            <svg className='tile-btn' width='20' height='20' viewBox='0 0 20 20' xmlns='http://www.w3.org/2000/svg'>
свг импортируй как картинку. посмотри по всему коду

2023-01-31 17:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/TatianaRusak/1675187214/content-window.png)

2023-01-31 17:50 UTC, SergeyGlazun approved these changes

2023-01-31 19:00 UTC, klichkovskiy approved these changes

2023-01-31 19:06 UTC, merged